
a = {1,2,3,4,5,6,7,8,10}
b = {4,5,6,7,8,9,10,11,12}
c = {8,9,10,11,12,13,14,15}
print('conjunto de numeros          ' , a)
print('2do conjunto de numeros      ' , b)
print('3er conjunto de numero       ' , c)
print("")
d = {'a','b','c','d','e','f'}
e = {'a','g','h','i','j','k'}
f = {'a','b','c'}
print('conjunto de letras           ' , d)
print('2do conjunto de letras       ' , e)
print('3er conjunto de letras       ' , f)
print("")
nombres = {'Ana','Maria','Jose','Gabriel','Pablo',"Rosa"}
nombres_2 = {'Pablo','Sandra','Gabriela','Rosa'}
print('conjunto de nombres          ' , nombres)
print('2do conjunto de nombres      ' , nombres_2)
print("")
colores = {'verde','rojo','amarillo','marron','azul','Rosa'}
colores_2 = {'Rosa','rosado','violeta','negro','gris','azul','verde'}
print("Conjunto de colores          " , colores)
print("Segundo conjunto de colores  " , colores_2)
print("")

#union de conjuntos denotado como | y tambien usando el metodo .union()
print("")
print(">Union de conjuntos de tres conjuntos")
print("")
print("*Union de a, b y c")
print(a|b|c)
print("*Union de c, d y a")
print(c|d|a)
print("")
print("*Union de nombres, nombres_2 y colores")
print(nombres|nombres_2|colores)
print("*Union de colores, nombres_2 y nombres")
print(colores|colores_2|nombres)
print("")
print("*Union de a, b y c")
print(a.union(b,c))
print("*Union de c, d y a")
print(c.union(d,a))
print("")
print("*Union de nombres, nombres_2 y colores")
print(nombres.union(nombres_2, colores))
print("*Union de colores, colores_2 y nombres")
print(colores.union(colores_2, nombres))
print("")

#interseccion de conjuntos denotado como &
print("")
print(">Interseccion de tres conjuntos")
print("")
print("*Interseccion de a, b y c")
intersection = a.intersection(b, c)
print(intersection)
print(len(intersection))
print("*Interseccion de c, d y a")
print("")
print("*Interseccion de nombres, nombre_2 y colores")
interseccion_2 = nombres.intersection(nombres_2, colores)
print(interseccion_2)
print(len(interseccion_2))
print("*Interseccion de colores, colores_2 y nombres")
interseccion_3 = colores.intersection(colores_2, nombres)
print(interseccion_3)
print(len(interseccion_3))

#diferencia de conjuntos denotado como - y .difference()
print("")
print(">Diferencia de dos conjuntos")
print("")
print("*Diferencia entre a y b")
print(a-b)
print("*Diferencia entre c y d")
print(c-d)
print("")
print("*Diferencia entre a y b")
print(a.difference(b))
print("*Diferencia entre c y d")
print(c.difference(d))
print("")
print("*Diferencia entre nombres y 2do conjunto de nombres")
print(nombres.difference(nombres_2))
print(colores.difference(colores_2))
